### PR TITLE
Upgrade to ruby 2.1.5

### PR DESCRIPTION
**Pull request by ryansch**
I don't have any other flavors of ruby installed and rails 4 works great with 2.1.2.  The development server starts and serves pages just fine.

### CODE REVIEW

**Comment by speric** [comment]
Hey @ryansch, sorry it's taken so long to get back to this.

Looks like `2.1.6` is on Heroku (https://devcenter.heroku.com/changelog-items/636). Do you want to update this PR to use that version (rebase, squash, etc.) and then I can merge it in?

**Comment by ryansch** [comment]
How do you feel about 2.2.2: https://devcenter.heroku.com/changelog-items/635

**Comment by speric** [comment]
Not opposed, as long as everything still works!

**Comment by speric** [comment]
@ryansch we just upgraded to Ruby 2.1.6, so I'm going to close this issue.

**Pull request closed without merging**
